export { default as Header } from "./Header/Header"
export { default as Footer } from "./Footer/Footer"
export { default as ProductDetails } from "./ProductDetails/ProductDetails"
export { default as CustomCategory } from "./CustomCategory/CustomCategory"
export { default as Product } from "./Product/Product"
export { default as Categorys } from "./Categorys/Categorys"
export { default as NotFound } from "./NotFound/NotFound"
export { default as Cart } from "./Cart/Cart"
export { default as CartTemplate } from "./CartTemplate/CartTemplate"
export { default as PrivateRoute } from "./PrivateRoute/PrivateRoute"
export { default as AdminProducts } from "./AdminProducts/AdminProducts"
export { default as Login } from "./Login/Login"
export { default as AdminOrders } from "./AdminOrders/AdminOrders"
export { default as Skeleton } from "./SkeletonPage/SkeletonPage"
export { default as Checkout } from "./Checkout/Checkout"
export { default as AdminOrderDone } from "./AdminOrderDone/AdminOrderDone"
export { default as Menu } from "./Menu/Menu"
export { default as PanelProductAdd } from "./PanelProductAdd/PanelProductAdd"
export { default as ScrollToTop } from "./ScrollToTop/ScrollToTop"
export { default as Swiper } from "./Swipers/Swipers"

// pages
export { default as Index } from "./../pages/Index/Index"
export { default as ProductInfo } from "./../pages/ProductInfo/ProductInfo"
export { default as CartPage } from "./../pages/CartPage/CartPage"

// other
export { default as ProductsContext } from "./../context/ProductContext"
export { default as routes } from "./../routes"
